services:
  push-server:
    container_name: push-server
    image: xct258/push-server
    network_mode: host
    volumes:
      - ./data:/rec        # 数据目录（配置/数据库/日志）
    environment:
      - MQTT_WS_PORT=9001  # mqtt的ws端口
      - UVICORN_PORT=8383  # fastapi的端口
    restart: always
